const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
    studentId: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    // faceDescriptor stores the 128 float values generated by face-api.js
    faceDescriptor: { type: [Number], required: true },
    attendance: [
        {
            date: { type: String, required: true }, // Format: YYYY-MM-DD
            timestamp: { type: Date, default: Date.now }
        }
    ]
});

module.exports = mongoose.model('Student', studentSchema);